export const FIELD_NORMGROESSE_TYPE = [
  { value: "KA", label: "Keine Angabe" },
  { value: "KTP", label: "Keine therapiegerechte Packungsgröße" },
  { value: "N1", label: "N1" },
  { value: "N2", label: "N2" },
  { value: "N3", label: "N3" },
  { value: "NB", label: "Nicht betroffen" },
  { value: "Sonstiges", label: "Sonstiges" }
];
//awk '{printf "{ value: \""$1"\", label: \""$1; $1 = ""; print " -" $0 "\" },"}'
export const FIELD_DARREICH_TYPE = [
  { value: "", label: "" },
  { value: "AEO", label: "AEO - Ätherisches Öl" },
  { value: "AMP", label: "AMP - Ampullen" },
  { value: "APA", label: "APA - Ampullenpaare" },
  { value: "ASN", label: "ASN - Augen- und Nasensalbe" },
  { value: "ASO", label: "ASO - Augen- und Ohrensalbe" },
  { value: "ATO", label: "ATO - Augen- und Ohrentropfen" },
  { value: "ATR", label: "ATR - Augentropfen" },
  { value: "AUB", label: "AUB - Augenbad" },
  { value: "AUC", label: "AUC - Augencreme" },
  { value: "AUG", label: "AUG - Augengel" },
  { value: "AUS", label: "AUS - Augensalbe" },
  { value: "BAD", label: "BAD - Bad" },
  { value: "BAL", label: "BAL - Balsam" },
  { value: "BAN", label: "BAN - Bandage" },
  { value: "BEU", label: "BEU - Beutel" },
  { value: "BIN", label: "BIN - Binden" },
  { value: "BON", label: "BON - Bonbons" },
  { value: "BPL", label: "BPL - Basisplatte" },
  { value: "BRE", label: "BRE - Brei" },
  { value: "BTA", label: "BTA - Brausetabletten" },
  { value: "CRE", label: "CRE - Creme" },
  { value: "DFL", label: "DFL - Durchstechflaschen" },
  { value: "DIG", label: "DIG - Digitale Gesundheitsanwendungen" },
  { value: "DIL", label: "DIL - Dilution" },
  { value: "DIS", label: "DIS - Depot-Injektionssuspension" },
  { value: "DKA", label: "DKA - Dragees in Kalenderpackung" },
  { value: "DOS", label: "DOS - Dosieraerosol" },
  { value: "DRA", label: "DRA - Dragees" },
  { value: "DRM", label: "DRM - Dragees magensaftresistent" },
  { value: "DSC", label: "DSC - Dosierschaum" },
  { value: "DSS", label: "DSS - Dosierspray" },
  { value: "EDP", label: "EDP - Einzeldosis-Pipetten" },
  { value: "EIN", label: "EIN - Einreibung" },
  { value: "ELE", label: "ELE - Elektroden" },
  { value: "ELI", label: "ELI - Elixier" },
  { value: "EMU", label: "EMU - Emulsion" },
  { value: "ESS", label: "ESS - Essenz" },
  { value: "ESU", label: "ESU - Erwachsenen-Suppositorien" },
  { value: "EXT", label: "EXT - Extrakt" },
  { value: "FBE", label: "FBE - Filterbeutel" },
  { value: "FBW", label: "FBW - Franzbranntwein" },
  { value: "FDA", label: "FDA - Filmdragees" },
  { value: "FER", label: "FER - Fertigspritzen" },
  { value: "FET", label: "FET - Fettsalbe" },
  { value: "FLA", label: "FLA - Flasche" },
  { value: "FLE", label: "FLE - Flüssigkeit zum Einnehmen" },
  { value: "FLU", label: "FLU - Flüssig" },
  { value: "FMR", label: "FMR - Filmtabletten magensaftresistent" },
  { value: "FOL", label: "FOL - Folie" },
  { value: "FRB", label: "FRB - Beutel mit retardierten Filmtabletten" },
  { value: "FSE", label: "FSE - Flüssigseife" },
  { value: "FTA", label: "FTA - Filmtabletten" },
  { value: "GEK", label: "GEK - Granulat zur Entnahme aus Kapseln" },
  { value: "GEL", label: "GEL - Gel" },
  { value: "GLI", label: "GLI - Gas und Lösungsmittel zur Herstellung einer Injektions-/Infusionsdispersion" },
  { value: "GLO", label: "GLO - Globuli" },
  { value: "GMR", label: "GMR - Magensaftresistentes Granulat" },
  { value: "GPA", label: "GPA - Gelplatte" },
  { value: "GRA", label: "GRA - Granulat" },
  { value: "GSE", label: "GSE - Granulat zur Herstellung einer Suspension zum Einnehmen" },
  { value: "GUL", label: "GUL - Gurgellösung" },
  { value: "HAS", label: "HAS - Handschuhe" },
  { value: "HKM", label: "HKM - Magensaftresistente Hartkapseln" },
  { value: "HKP", label: "HKP - Hartkapseln" },
  { value: "HPI", label: "HPI - Hartkapseln mit Pulver zur Inhalation" },
  { value: "HVW", label: "HVW - Hartkapseln mit veränderter Wirkstofffreisetzung" },
  { value: "IFA", label: "IFA - Infusionsampullen" },
  { value: "IFB", label: "IFB - Infusionsbeutel" },
  { value: "IFD", label: "IFD - Infusionsdispersion" },
  { value: "IFE", label: "IFE - Injektionslösung in einer Fertigspritze" },
  { value: "IFF", label: "IFF - Infusionsflaschen" },
  { value: "IFK", label: "IFK - Infusionslösungskonzentrat" },
  { value: "IFL", label: "IFL - Injektionsflaschen" },
  { value: "IFS", label: "IFS - Infusionsset" },
  { value: "IHA", label: "IHA - Inhalationsampullen" },
  { value: "IHP", label: "IHP - Inhalationspulver" },
  { value: "IIE", label: "IIE - Injektions- oder Infusionslösung oder Lösung zum Einnehmen" },
  { value: "IIL", label: "IIL - Injektions-, Infusionslösung" },
  { value: "IIM", label: "IIM - Injektionslösung zur intramuskulären Anwendung" },
  { value: "IKA", label: "IKA - Inhalationskapseln" },
  { value: "ILO", label: "ILO - Injektionslösung" },
  { value: "IMP", label: "IMP - Implantat" },
  { value: "INF", label: "INF - Infusionslösung" },
  { value: "INH", label: "INH - Inhalat" },
  { value: "INI", label: "INI - Injektions-, Infusionsflaschen" },
  { value: "INL", label: "INL - Inhalationslösung" },
  { value: "INS", label: "INS - Instant-Tee" },
  { value: "IST", label: "IST - Instillation" },
  { value: "ISU", label: "ISU - Injektionssuspension" },
  { value: "IUP", label: "IUP - Intrauterinpessar" },
  { value: "KAN", label: "KAN - Kanülen" },
  { value: "KAP", label: "KAP - Kapseln" },
  { value: "KAT", label: "KAT - Katheter" },
  { value: "KDA", label: "KDA - Kaudragees" },
  { value: "KEG", label: "KEG - Kegel" },
  { value: "KER", label: "KER - Kerne" },
  { value: "KGU", label: "KGU - Kaugummi" },
  { value: "KID", label: "KID - Konzentrat zur Herstellung einer Infusionsdispersion" },
  { value: "KII", label: "KII - Konzentrat zur Herstellung einer Injektions- oder Infusionslösung" },
  { value: "KKS", label: "KKS - Kleinkinder-Suppositorien" },
  { value: "KLI", label: "KLI - Klistiere" },
  { value: "KLT", label: "KLT - Klistier-Tabletten" },
  { value: "KMP", label: "KMP - Hartkapseln mit magensaftresistent überzogenen Pellets" },
  { value: "KMR", label: "KMR - Kapseln magensaftresistent" },
  { value: "KOD", label: "KOD - Kondome" },
  { value: "KOM", label: "KOM - Kompressen" },
  { value: "KON", label: "KON - Konzentrat" },
  { value: "KPG", label: "KPG - Kombipackung" },
  { value: "KRI", label: "KRI - Kristallsuspension" },
  { value: "KSS", label: "KSS - Kinder- und Säuglings-Suppositorien" },
  { value: "KSU", label: "KSU - Kinder-Suppositorien" },
  { value: "KTA", label: "KTA - Kautabletten" },
  { value: "LAN", label: "LAN - Lanzetten" },
  { value: "LII", label: "LII - Lösung zur Injektion, Infusion und Inhalation" },
  { value: "LIQ", label: "LIQ - Liquidum" },
  { value: "LOE", label: "LOE - Lösung" },
  { value: "LOT", label: "LOT - Lotion" },
  { value: "LOV", label: "LOV - Lösung für einen Vernebler" },
  { value: "LSE", label: "LSE - Lösung zum Einnehmen" },
  { value: "LTA", label: "LTA - Lacktabletten" },
  { value: "LUP", label: "LUP - Lutschpastillen" },
  { value: "LUT", label: "LUT - Lutschtabletten" },
  { value: "MIL", label: "MIL - Milch" },
  { value: "MIS", label: "MIS - Mischung" },
  { value: "MIX", label: "MIX - Mixtur" },
  { value: "MRG", label: "MRG - Magensaftresistentes Retardgranulat" },
  { value: "MRP", label: "MRP - Magensaftresistente Pellets" },
  { value: "MTA", label: "MTA - Manteltabletten" },
  { value: "MUW", label: "MUW - Mundwasser" },
  { value: "NAG", label: "NAG - Nasengel" },
  { value: "NAO", label: "NAO - Nasenöl" },
  { value: "NAS", label: "NAS - Nasenspray" },
  { value: "NAW", label: "NAW - Wirkstoffhaltiger Nagellack" },
  { value: "NDS", label: "NDS - Nasendosierspray" },
  { value: "NSA", label: "NSA - Nasensalbe" },
  { value: "NTR", label: "NTR - Nasentropfen" },
  { value: "OCU", label: "OCU - Ocusert" },
  { value: "OEL", label: "OEL - Öl" },
  { value: "OHT", label: "OHT - Ohrentropfen" },
  { value: "OVU", label: "OVU - Ovula" },
  { value: "PAM", label: "PAM - Packungsmasse" },
  { value: "PAS", label: "PAS - Pastillen" },
  { value: "PEL", label: "PEL - Pellets" },
  { value: "PEN", label: "PEN - Injektionslösung in einem Fertigpen" },
  { value: "PER", label: "PER - Perlen" },
  { value: "PFL", label: "PFL - Pflaster" },
  { value: "PFT", label: "PFT - Pflaster transdermal" },
  { value: "PHI", label: "PHI - Pulver zur Herstellung einer Injektions-, Infusions- oder Inhalationslösung" },
  { value: "PHV", label: "PHV - Pulver zur Herstellung einer Injektions- bzw. Infusionslösung oder Pulver und Lösungsmittel zur Herstellung einer Lösung zur intravesikalen Anwendung" },
  { value: "PIE", label: "PIE - Pulver für ein Konzentrat zur Herstellung einer Infusionslösung, Pulver zur Herstellung einer Lösung zum Einnehmen" },
  { value: "PIF", label: "PIF - Pulver für ein Konzentrat zur Herstellung einer Infusionslösung, Pulver zur Herstellung einer Lösung zum Einnehmen" },
  { value: "PII", label: "PII - Pulver zur Herstellung einer Injektions- oder Infusionslösung" },
  { value: "PIJ", label: "PIJ - Pulver zur Herstellung einer Injektionslösung" },
  { value: "PIK", label: "PIK - Pulver zur Herstellung eines Infusionslösungskonzentrates" },
  { value: "PIS", label: "PIS - Pulver zur Herstellung einer Infusionssuspension" },
  { value: "PIV", label: "PIV - Pulver zur Herstellung einer Injektions- bzw. Infusionslösung oder einer Lösung zur intravesikalen Anwendung" },
  { value: "PKI", label: "PKI - Pulver für ein Konzentrat zur Herstellung einer Infusionslösung" },
  { value: "PLE", label: "PLE - Pulver zur Herstellung einer Lösung zum Einnehmen" },
  { value: "PLF", label: "PLF - Pulver und Lösungsmittel zur Herstellung einer Infusionslösung" },
  { value: "PLG", label: "PLG - Perlongetten" },
  { value: "PLH", label: "PLH - Pulver und Lösungsmittel zur Herstellung einer Injektions- bzw. Infusionslösung" },
  { value: "PLI", label: "PLI - Pulver und Lösungsmittel zur Herstellung einer Injektionslösung" },
  { value: "PLK", label: "PLK - Pulver und Lösungsmittel für ein Konzentrat zur Herstellung einer Infusionslösung" },
  { value: "PLS", label: "PLS - Pulver und Lösungsmittel zur Herstellung einer Injektionssuspension" },
  { value: "PLV", label: "PLV - Pulver und Lösungsmittel zur Herstellung einer Lösung zur intravesikalen Anwendung" },
  { value: "PPL", label: "PPL - Pumplösung" },
  { value: "PRS", label: "PRS - Presslinge" },
  { value: "PSE", label: "PSE - Pulver zur Herstellung einer Suspension zum Einnehmen" },
  { value: "PST", label: "PST - Paste" },
  { value: "PUD", label: "PUD - Puder" },
  { value: "PUL", label: "PUL - Pulver" },
  { value: "RED", label: "RED - Retard-Dragees" },
  { value: "REK", label: "REK - Retard-Kapseln" },
  { value: "RET", label: "RET - Retard-Tabletten" },
  { value: "RGR", label: "RGR - Retard-Granulat" },
  { value: "RKA", label: "RKA - Retard-Kapseln" },
  { value: "RMS", label: "RMS - Retardmikrokapseln und Suspensionsmittel" },
  { value: "RSC", label: "RSC - Rektalschaum" },
  { value: "RSU", label: "RSU - Rektalsuspension" },
  { value: "RUT", label: "RUT - Retard-überzogene Tabletten" },
  { value: "SAF", label: "SAF - Saft" },
  { value: "SAL", label: "SAL - Salbe" },
  { value: "SAM", label: "SAM - Salbe zur Anwendung in der Mundhöhle" },
  { value: "SCH", label: "SCH - Schaum" },
  { value: "SEI", label: "SEI - Seife" },
  { value: "SHA", label: "SHA - Shampoo" },
  { value: "SIR", label: "SIR - Sirup" },
  { value: "SLZ", label: "SLZ - Salz" },
  { value: "SMF", label: "SMF - Schmelzfilm" },
  { value: "SMT", label: "SMT - Schmelztabletten" },
  { value: "SMU", label: "SMU - Suppositorien mit Mulleinlage" },
  { value: "SPA", label: "SPA - Spritzampullen" },
  { value: "SPF", label: "SPF - Sprühflasche" },
  { value: "SPL", label: "SPL - Spüllösung" },
  { value: "SPR", label: "SPR - Spray" },
  { value: "SPT", label: "SPT - Transdermales Spray" },
  { value: "SRI", label: "SRI - Spritzen" },
  { value: "SSU", label: "SSU - Säuglings-Suppositorien" },
  { value: "STA", label: "STA - Stechampullen" },
  { value: "STB", label: "STB - Stäbchen" },
  { value: "STI", label: "STI - Stifte" },
  { value: "STR", label: "STR - Streifen" },
  { value: "SUB", label: "SUB - Substanz" },
  { value: "SUE", label: "SUE - Suspension zum Einnehmen" },
  { value: "SUL", label: "SUL - Sublingualspray, Lösung" },
  { value: "SUP", label: "SUP - Suppositorien" },
  { value: "SUS", label: "SUS - Suspension" },
  { value: "SUT", label: "SUT - Sublingualtabletten" },
  { value: "SUV", label: "SUV - Suspension für einen Vernebler" },
  { value: "SWA", label: "SWA - Schwämme" },
  { value: "TAB", label: "TAB - Tabletten" },
  { value: "TAE", label: "TAE - Täfelchen" },
  { value: "TAM", label: "TAM - Trockenampullen" },
  { value: "TEE", label: "TEE - Tee" },
  { value: "TEI", label: "TEI - Tropfen zum Einnehmen" },
  { value: "TES", label: "TES - Test" },
  { value: "TIN", label: "TIN - Tinktur" },
  { value: "TKA", label: "TKA - Tabletten in Kalenderpackung" },
  { value: "TLE", label: "TLE - Tablette zur Herstellung einer Lösung zum Einnehmen" },
  { value: "TMR", label: "TMR - Tabletten magensaftresistent" },
  { value: "TON", label: "TON - Tonikum" },
  { value: "TPN", label: "TPN - Tampon" },
  { value: "TPO", label: "TPO - Tamponaden" },
  { value: "TRA", label: "TRA - Trinkampullen" },
  { value: "TRI", label: "TRI - Trituration" },
  { value: "TRO", label: "TRO - Tropfen" },
  { value: "TRS", label: "TRS - Trockensubstanz mit Lösungsmittel" },
  { value: "TRT", label: "TRT - Trinktabletten" },
  { value: "TSA", label: "TSA - Trockensaft" },
  { value: "TSD", label: "TSD - Tabletten zur Herstellung einer Suspension zum Einnehmen für einen Dosierspender" },
  { value: "TSE", label: "TSE - Tablette zur Herstellung einer Suspension zum Einnehmen" },
  { value: "TSS", label: "TSS - Trockensubstanz ohne Lösungsmittel" },
  { value: "TST", label: "TST - Teststäbchen" },
  { value: "TSY", label: "TSY - Transdermales System" },
  { value: "TTR", label: "TTR - Teststreifen" },
  { value: "TUB", label: "TUB - Tube" },
  { value: "TUE", label: "TUE - Tücher" },
  { value: "TUP", label: "TUP - Tupfer" },
  { value: "TVW", label: "TVW - Tablette mit veränderter Wirkstofffreisetzung" },
  { value: "UTA", label: "UTA - Überzogene Tabletten" },
  { value: "VAL", label: "VAL - Vaginallösung" },
  { value: "VAR", label: "VAR - Vaginalring" },
  { value: "VCR", label: "VCR - Vaginalcreme" },
  { value: "VER", label: "VER - Verband" },
  { value: "VGE", label: "VGE - Vaginalgel" },
  { value: "VKA", label: "VKA - Vaginalkapseln" },
  { value: "VLI", label: "VLI - Vlies" },
  { value: "VOV", label: "VOV - Vaginalovula" },
  { value: "VST", label: "VST - Vaginalstäbchen" },
  { value: "VSU", label: "VSU - Vaginalsuppositorien" },
  { value: "VTA", label: "VTA - Vaginaltabletten" },
  { value: "WAT", label: "WAT - Watte" },
  { value: "WGA", label: "WGA - Wundgaze" },
  { value: "WKA", label: "WKA - Weichkapseln" },
  { value: "WKM", label: "WKM - Magensaftresistente Weichkapseln" },
  { value: "WUE", label: "WUE - Würfel" },
  { value: "XDG", label: "XDG - Duschgel" },
  { value: "XDS", label: "XDS - Deo-Spray" },
  { value: "XFE", label: "XFE - Festiger" },
  { value: "XGM", label: "XGM - Gesichtsmaske" },
  { value: "XHA", label: "XHA - Halsband" },
  { value: "XHS", label: "XHS - Haarspülung" },
  { value: "XNC", label: "XNC - Nachtcreme" },
  { value: "XPK", label: "XPK - Körperpflege" },
  { value: "XTC", label: "XTC - Tagescreme" },
  { value: "ZAM", label: "ZAM - Zylinderampullen" },
  { value: "ZBU", label: "ZBU - Zahnbürste" },
  { value: "ZCR", label: "ZCR - Zahncreme" },
  { value: "ZGE", label: "ZGE - Zahngel" },
  { value: "ZKA", label: "ZKA - Zerbeisskapseln" },
  { value: "ZPA", label: "ZPA - Zahnpasta" }
];
